huygenstemp<-read.csv("HASI_L4_TEM_TEMPERATURE-TAB.csv")
huygenspres<-read.csv("HASI_L4_PPI_PRESSURE_VEL-TAB.csv")
head(huygenstemp)
head(huygenspres)
htp<-merge(huygenstemp,huygenspres,by=c('TIME..MILLISECONDS.'),all.x=T)
View(htp)
write.csv(htp,"C:/Users/sdbar/Box Sync/HUYGENS/csv FOR DA\\HuygensPresTempMerge.csv",row.names=FALSE)
huygenszonalwind<-read.csv("ZONALWIND-TAB.csv")
huygensmolefraction<-read.csv("GCMS_MOLE_FRACTION_STG2-TAB.csv")
head(huygenszonalwind)
head(huygensmolefraction)
hwm<-merge(huygenszonalwind,huygensmolefraction,by=c('X..........UTC_ABS_TIME.'),all.x=T)
write.csv(hwm,"C:/Users/sdbar/Box Sync/HUYGENS/csv FOR DA\\HuygensZonalWindMoleFracMerge.csv",row.names=FALSE)
